/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#101b34",
        "on-tertiary-container": "#dae7ff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "focus-ring": "#1C7ED6",
        "safe-bg": "#EBFBEE",
        "on-secondary-container": "#56607d",
        "primary": "#1a40c2",
        "tertiary": "#00518f",
        "highrisk-bg": "#FFF0F0",
        "inverse-primary": "#b8c3ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#e2e5ff",
        "secondary": "#545e7a",
        "surface-container-lowest": "#ffffff",
        "safe-text": "#1B5E2B",
        "primary-subtle": "#EDF2FF",
        "on-error": "#ffffff",
        "surface": "#FFFFFF",
        "secondary-container": "#d2dcfe",
        "surface-container-low": "#f2f3ff",
        "surface-variant": "#dce1fc",
        "primary-hover": "#324ABF",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#0069b8",
        "surface-tint": "#3052d2",
        "surface-dim": "#d4d9f3",
        "primary-container": "#3b5bdb",
        "secondary-fixed": "#dae2ff",
        "on-error-container": "#93000a",
        "primary-fixed": "#dde1ff",
        "border": "#D9DEEA",
        "highrisk-main": "#C92A2A",
        "inverse-on-surface": "#eef0ff",
        "tertiary-fixed": "#d3e4ff",
        "highrisk-text": "#8A1C1C",
        "background": "#F8F9FC",
        "on-secondary-fixed-variant": "#3c4661",
        "on-secondary": "#ffffff",
        "outline": "#747686",
        "surface-container-high": "#e3e7ff",
        "on-primary-fixed": "#001355",
        "surface-container-highest": "#dce1fc",
        "surface-container": "#ebedff",
        "on-surface": "#151b2e",
        "on-tertiary-fixed": "#001c38",
        "suspicious-main": "#E67700",
        "primary-fixed-dim": "#b8c3ff",
        "suspicious-text": "#7A4100",
        "on-primary-fixed-variant": "#0736ba",
        "safe-main": "#2B8A3E",
        "tertiary-fixed-dim": "#a2c9ff",
        "on-background": "#151b2e",
        "outline-variant": "#c4c5d6",
        "inverse-surface": "#2a3043",
        "secondary-fixed-dim": "#bcc6e7",
        "surface-bright": "#faf8ff",
        "on-tertiary-fixed-variant": "#004881",
        "on-surface-variant": "#444654",
        "suspicious-bg": "#FFF4E0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
};
